### ISSUE TITLE
Generate CMake file

### ISSUE THREAD

**Issue by liavt** [liavt/MACE#1]
In order for automated unit testing, we need a Makefile to build on Unix.

**Comment by sharhar** [comment]
we should try to figure out a way to generate one based on the visual studio project files so that it updates when we add new files automatically. I think i could write a python script to do it. but it would take a lot of time

**Comment by liavt** [comment]
I tried looking into that, and there seems to be no tool for VS 2015. There is one for 2013, and hasn't been updated, so we may want to modify that

**Comment by sharhar** [comment]
Can you give me a link to that script?

**Comment by liavt** [comment]
There are actually 3:
- https://code.google.com/archive/p/make-it-so/ (last updated for 2010)
- http://www.codeproject.com/Articles/28908/Tool-for-Converting-VC-2005-Project-to-Linux-Makef (last updated for 2005)
- https://sourceforge.net/projects/vcproj2cmake/ (unknown when last updated for)

I think that modifying these scripts would be harder than just to manually create a Makefile. VS has an option to read Makefiles, but can't create them.

**Comment by liavt** [comment]
Plus, CMake has an option to do "directories," where it will generate a Makefile for all files in a directory, so you don't have to manually add them.

**Comment by liavt** [comment]
Basically done.
