### ISSUE TITLE
Example games

### ISSUE THREAD

**Issue by sharhar** [liavt/MACE#5]
It's very difficult to understand how to use the engine if there aren't any example games in the repo. even just a simple pong game would help a lot in trying to understand how to use it.

**Comment by liavt** [comment]
I agree, but it is no where near completion to do such a thing. It doesn't even have mouse input yet

**Comment by sharhar** [comment]
Still, anything would help. I want to continue helping you develope the engine but its hard to do that if I have no way of figuring out how to use it.

**Comment by liavt** [comment]
I agree. I will work on documentation soon once the basics are done.

**Comment by sharhar** [comment]
Liva, why the hell aren't you on steam or skype?

**Comment by liavt** [comment]
I am just too busy all the time

**Comment by sharhar** [comment]
go on steam now

**Comment by sharhar** [comment]
so that we can at least chat

**Comment by liavt** [comment]
I created a folder for demos and I will start adding stuff to it.

**Comment by sharhar** [comment]
Thanks!

I'll look at it when I can.

**Comment by liavt** [comment]
I have created some demos
