### ISSUE TITLE
Libraries don't download

### ISSUE THREAD

**Issue by sharhar** [liavt/MACE#6]
When initially running the cmake project to generate build files, external libraries aren't downloaded if they are not found. This should be fixed to allow for the engine to be used with ease by other people.

**Comment by sharhar** [comment]
Also, GET ON STEAM LIAV!

**Comment by liavt** [comment]
I got rid of

**Comment by liavt** [comment]
I got rid of the automatic downloading because it cluttered the CMake file, and on non-Windows system it is very easy to install external libraries. On Windows, you need to set the _INCLUDE and _LIBRARY variables for each external library.

**Comment by sharhar** [comment]
How would I set that?

**Comment by sharhar** [comment]
Also, having the libraries download allows us to make sure that the correct version of the libraries is being used for the compilation. How do you know that someone doesn't have an older version?

**Comment by liavt** [comment]
Having the libraries download will create a redundancy however. If the person already has the library installed, they don't need to sit there while it downloads and compiles.

And to set the CMake variables, you need to use CMake GUI or the -D command

**Comment by sharhar** [comment]
At least give the user the option. You already had the functionality, it doesn't make any sense to remove a feature when people will use it.

**Comment by liavt** [comment]
Ok. I will reopen this and work on it later

**Comment by liavt** [comment]
I readded it, with the ability to easily add more libraries. Try now.

**Comment by liavt** [comment]
Issue will be closed when unit tests pass

**Comment by liavt** [comment]
Done.

**Comment by sharhar** [comment]
Thanks! I can now try to figure out how this engine works and hopefully help out.
