### ISSUE TITLE
Add a UI labrary

### ISSUE THREAD

**Issue by sharhar** [liavt/MACE#8]
Add the GLUI library as a dependency for MACE and use it to render UI.

**Comment by liavt** [comment]
I already made a UI library. If you want to, you can still add it. The only thing I don't have from GLUI is your graphs - that would be awesome to have in MACE.

**Comment by liavt** [comment]
There is a special API to add UI elements. If you want to learn what it is tell me.

**Comment by sharhar** [comment]
What UI API are you talking about? Also, you want to add graphing functionality to a game engine?

**Comment by liavt** [comment]
The UI api I made. Also, I want to use it for anything, not only games. Some games have graphs anyways. You already have it programmed in OpenGL 3.3 so I don't think it would be difficult

**Comment by sharhar** [comment]
The graphing thing that I made can only be used to graph mathematical functions. If you really want I could try to figure out a way to put it in, but I'm not sure how graphing a sine wave will help MACE.
